name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      channel:
        description: 'Release channel'
        required: true
        default: 'stable'

env:
  # Common users. We can't run a step 'if secrets.DOCKER_USR != ""' but we can run
  # a step 'if env.DOCKER_USR' != ""', so we copy these to succinctly test whether
  # credentials have been provided before trying to run steps that need them.
  DOCKER_USR: ${{ secrets.DOCKER_USR }}
<<<<<<< HEAD
=======
  UPBOUND_CROSSPLANE_ROBOT_USR: ${{ secrets.UPBOUND_CROSSPLANE_ROBOT_USR }}
  AWS_USR: ${{ secrets.AWS_USR }}
>>>>>>> upstream/release-1.4

jobs:
  promote-artifacts:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: env.DOCKER_USR != ''
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PSW }}
        
      - name: Login to Upbound Registry
        uses: docker/login-action@v1
        if: env.UPBOUND_CROSSPLANE_ROBOT_USR != ''
        with:
          registry: registry.upbound.io
          username: ${{ secrets.UPBOUND_CROSSPLANE_ROBOT_USR }}
          password: ${{ secrets.UPBOUND_CROSSPLANE_ROBOT_PSW }}

      - name: Promote Artifacts in Docker Hub
        run: make -j2 promote BRANCH_NAME=${GITHUB_REF##*/}
        env:
          VERSION: ${{ github.event.inputs.version }}
          CHANNEL: ${{ github.event.inputs.channel }}
